version: '3.8'

services:
    nginx:
        restart: always
        build:
            context: ./compose/local/nginx
            dockerfile: Dockerfile
        ports:
            - '3050:80'

    backend:
        build:
            context: .
            dockerfile: ./compose/test/backend/Dockerfile
        # '/start.sh' is the shell script used to run the service
        command: /start.sh
        ports:
            - 8000:8000
        # env_file is used to manage the env variables of project
        environment:
            - DJANGO_SECRECT_KEY=${DJANGO_SECRECT_KEY}
            - DJANGO_ENV=development
            - DJANGO_MEMCACHE=dummy
            - REDIS_URL=redis://redis:6379/1
            - DB_MANAGEMENT=postgres
            - DB_HOST=db
            - DB_PORT=5432
            - DB_NAME=media_review_app_test
            - DB_USER=myuser
            - DB_PASSWORD=mypass
            - CD_NAME=testname
            - CD_API_KEY=testkey
            - CD_API_SECRET=testsecret
            - CD_API_ENV_VAR=testvar
        depends_on:
            - redis
            - db

    db:
        image: postgres:14-alpine
        environment:
            - POSTGRES_DB=media_review_app_test
            - POSTGRES_USER=myuser
            - POSTGRES_PASSWORD=mypass

    redis:
        image: redis:6-alpine

    celery_worker:
        build:
            context: .
            dockerfile: ./compose/test/backend/Dockerfile
        command: /start-celery-worker.sh
        environment:
            - DJANGO_SECRECT_KEY=${DJANGO_SECRECT_KEY}
            - DJANGO_ENV=development
            - DJANGO_MEMCACHE=dummy
            - REDIS_URL=redis://redis:6379/1
            - DB_MANAGEMENT=postgres
            - DB_HOST=db
            - DB_PORT=5432
            - DB_NAME=media_review_app_test
            - DB_USER=myuser
            - DB_PASSWORD=mypass
        depends_on:
            - redis
            - db

    celery_flower:
        build:
            context: .
            dockerfile: ./compose/test/backend/Dockerfile
        command: /start-celery-flower.sh
        environment:
            - DJANGO_SECRECT_KEY=${DJANGO_SECRECT_KEY}
            - DJANGO_ENV=development
            - DJANGO_MEMCACHE=dummy
            - REDIS_URL=redis://redis:6379/1
            - DB_MANAGEMENT=postgres
            - DB_HOST=db
            - DB_PORT=5432
            - DB_NAME=media_review_app_test
            - DB_USER=myuser
            - DB_PASSWORD=mypass
        ports:
            - 5558:5555
        depends_on:
            - redis
            - db

    # Flask service for cypress to flush and load data on database
    flask:
        build:
            context: .
            dockerfile: ./compose/test/backend/Dockerfile
        command: /start-flask.sh
        environment:
            - DJANGO_SECRECT_KEY=${DJANGO_SECRECT_KEY}
            - DJANGO_ENV=development
            - DJANGO_MEMCACHE=dummy
            - REDIS_URL=redis://redis:6379/1
            - DB_MANAGEMENT=postgres
            - DB_HOST=db
            - DB_PORT=5432
            - DB_NAME=media_review_app_test
            - DB_USER=myuser
            - DB_PASSWORD=mypass
        ports:
            - 4000:4000
        depends_on:
            - redis
            - db

    frontend:
        build:
            context: .
            dockerfile: ./compose/test/frontend/Dockerfile
        command: /start.sh
        ports:
            - 3000:3000
        environment:
            - API_HOST=http://backend:8000
        depends_on:
            - backend

    cypress:
        build:
            context: .
            dockerfile: ./compose/test/e2e/Dockerfile
        depends_on:
            - backend
            - frontend
